import ccxt
import pandas as pd
import streamlit as st
import requests
import numpy as np
import plotly.graph_objects as go
from datetime import datetime

# 1. DATA ENGINE (CROSS-CHECKED & LOCKED)
@st.cache_data(ttl=15)
def fetch_institutional_data():
    try:
        exchange = ccxt.kraken()
        sol_bars = exchange.fetch_ohlcv('SOL/USD', timeframe='1d', limit=300)
        btc_bars = exchange.fetch_ohlcv('BTC/USD', timeframe='1d', limit=300)
        
        df = pd.DataFrame(sol_bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
        btc_df = pd.DataFrame(btc_bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        
        # CORE ELEMENT: Emmanuel's Moving Averages
        df['20_ema'] = df['close'].ewm(span=20, adjust=False).mean()
        df['200_sma'] = df['close'].rolling(window=200).mean()
        
        # CORE ELEMENT: ATR for Autogenerated Range
        df['tr'] = df[['high', 'low', 'close']].max(axis=1) - df[['high', 'low', 'close']].min(axis=1)
        df['atr'] = df['tr'].rolling(window=14).mean()
        
        # Institutional Alpha: BTC Correlation & RSI
        df['btc_corr'] = df['close'].rolling(window=30).corr(btc_df['close'])
        delta = df['close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        df['rsi'] = 100 - (100 / (1 + (gain / loss.replace(0, np.nan)).fillna(0)))
        
        # Volume POC
        df['poc'] = df.tail(20).loc[df.tail(20)['volume'].idxmax()]['close']
        
        # Fear & Greed Fallback
        try:
            fng_res = requests.get("https://api.alternative.me/fng/", timeout=5).json()
            fng_data = fng_res['data'][0]
        except:
            fng_data = {'value': '50', 'value_classification': 'Neutral'}

        return df, btc_df['close'].iloc[-1], fng_data, True
    except:
        return None, None, None, False

def play_alert_sound():
    # Invisible Audio Trigger
    audio_html = """
    <audio autoplay>
      <source src="https://www.soundjay.com/buttons/sounds/button-3.mp3" type="audio/mpeg">
    </audio>
    """
    st.markdown(audio_html, unsafe_allow_html=True)

def get_sreejan_forecaster():
    st.set_page_config(page_title="Sreejan Master Pro", layout="wide")
    
    # CLASSIC PROFESSIONAL STYLING
    st.markdown("""
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Roboto+Mono&display=swap');
        .stApp { background-color: #0A0A0B; color: #E0E0E0; }
        .metric-card { background: #111113; padding: 20px; border: 1px solid #222; border-radius: 4px; text-align: center; }
        h1, h2, h3 { font-family: 'Libre+Baskerville', serif; color: #D4AF37; }
        .mono { font-family: 'Roboto Mono', monospace; }
        .status-dot { height: 10px; width: 10px; border-radius: 50%; display: inline-block; margin-right: 8px; }
        
        /* HOVER INFO SYSTEM */
        .info-box { position: relative; display: inline-block; cursor: pointer; color: #854CE6; }
        .info-box .info-text {
            visibility: hidden; width: 220px; background-color: #1A1A1D; border: 1px solid #D4AF37;
            padding: 10px; border-radius: 5px; position: absolute; z-index: 10; bottom: 125%; left: 50%;
            margin-left: -110px; opacity: 0; transition: opacity 0.3s; color: #fff; font-size: 13px;
        }
        .info-box:hover .info-text { visibility: visible; opacity: 1; }
        </style>
    """, unsafe_allow_html=True)

    df, btc_price, fng, status = fetch_institutional_data()

    # --- TOP LEVEL STATUS & ALERTS ---
    t_col1, t_col2 = st.columns([8, 2])
    with t_col2:
        dot = "#00FFA3" if status else "#FF4B4B"
        st.markdown(f"<div style='text-align:right;'><span class='status-dot' style='background-color:{dot}'></span>Institutional Feed Live</div>", unsafe_allow_html=True)

    if df is not None:
        price = df['close'].iloc[-1]
        atr = df['atr'].iloc[-1]
        ema20 = df['20_ema'].iloc[-1]
        sma200 = df['200_sma'].iloc[-1]
        poc = df['poc'].iloc[-1]

        # --- BANNER ---
        cols = st.columns(5)
        with cols[0]: st.markdown(f"<div class='metric-card'><small>BTC</small><br><b class='mono'>₿ {btc_price:,.2f}</b></div>", unsafe_allow_html=True)
        with cols[1]: st.markdown(f"<div class='metric-card'><small>SOL</small><br><b class='mono'>🟣 {price:,.2f}</b></div>", unsafe_allow_html=True)
        with cols[2]: st.markdown(f"<div class='metric-card'><small>BTC CORR</small><br><b class='mono'>{df['btc_corr'].iloc[-1]:.2f}</b></div>", unsafe_allow_html=True)
        with cols[3]: st.markdown(f"<div class='metric-card'><small>VOLUME POC</small><br><b class='mono'>${poc:,.2f}</b></div>", unsafe_allow_html=True)
        with cols[4]:
            st.markdown(f"""
                <div class='metric-card'>
                    <div class='info-box'><small>SENTIMENT ℹ️</small>
                        <span class='info-text'>Fear & Greed Index: Determines if the market is overextended (Greed) or undervalued (Fear). Current: {fng['value_classification']}</span>
                    </div><br>
                    <b class='mono'>{fng['value']}</b>
                </div>
            """, unsafe_allow_html=True)

        # --- SIDEBAR CONFIG (CORE ELEMENTS) ---
        st.sidebar.title("🛠️ Strategy & Safety")
        capital = st.sidebar.number_input("Capital Allocation ($)", value=10000.0)
        lev = st.sidebar.select_slider("Leverage (45% Margin Safety Cap)", options=[1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0], value=1.5)
        bias_input = st.sidebar.selectbox("Macro Bias Multiplier", ["Bullish 🚀", "Neutral ⚖️", "Bearish 📉"])
        
        # --- CORE ELEMENT: LIQUIDATION PRICE ---
        # Rule: 45% margin safety rule for perp contracts
        liq_price = price * (1 - (1 / lev) * 0.45) if lev > 1.0 else 0
        st.sidebar.markdown(f"<div style='padding:10px; border:1px solid #FF4B4B; border-radius:5px;'><b>LIQUIDATION PRICE</b><br><span class='mono' style='color:#FF4B4B;'>${liq_price:,.2f}</span></div>", unsafe_allow_html=True)

        # --- EMMANUEL PERP SIGNAL (SOUND & TOAST) ---
        st.subheader("⚡ Signal Execution (Emmanuel-Logic)")
        if price > sma200 and price > ema20:
            sig, color = "STRONG LONG 🟢", "#00FFA3"
            entry, sl, tp1, tp2 = price * 1.002, price - (atr * 1.5), price + (atr * 1.5), price + (atr * 3)
            st.toast("SIGNAL: Strong Long Detected", icon="📈")
            play_alert_sound()
        elif price < sma200 and price < ema20:
            sig, color = "STRONG SHORT 🔴", "#FF4B4B"
            entry, sl, tp1, tp2 = price * 0.998, price + (atr * 1.5), price - (atr * 1.5), price - (atr * 3)
            st.toast("SIGNAL: Strong Short Detected", icon="📉")
            play_alert_sound()
        else:
            sig, color = "NEUTRAL ⚪", "#888"
            entry, sl, tp1, tp2 = price, price - atr, price + atr, price + (atr*2)

        st.markdown(f"""
        <table style="width:100%; border-collapse: collapse; border: 1px solid #333; font-family: 'Roboto Mono'; background-color: #0E1117;">
            <tr style="background-color: #1A1C23; color:#888;">
                <th>BIAS</th><th>ENTRY</th><th>STOP LOSS</th><th>TARGET 1</th><th>TARGET 2</th>
            </tr>
            <tr style="text-align: center; font-size: 18px;">
                <td style="padding: 20px; border: 1px solid #333; color: {color}; font-weight: bold;">{sig}</td>
                <td style="padding: 20px; border: 1px solid #333;">${entry:,.2f}</td>
                <td style="padding: 20px; border: 1px solid #333; color: #FF4B4B;">${sl:,.2f}</td>
                <td style="padding: 20px; border: 1px solid #333; color: #00FFA3;">${tp1:,.2f}</td>
                <td style="padding: 20px; border: 1px solid #333; color: #00FFA3;">${tp2:,.2f}</td>
            </tr>
        </table>
        """, unsafe_allow_html=True)

        # --- TACTICAL CHART ---
        fig = go.Figure()
        hist = df.tail(50)
        fig.add_trace(go.Candlestick(x=hist['date'], open=hist['open'], high=hist['high'], low=hist['low'], close=hist['close']))
        fig.add_trace(go.Scatter(x=hist['date'], y=hist['20_ema'], name='20 EMA', line=dict(color='#854CE6')))
        fig.add_trace(go.Scatter(x=hist['date'], y=hist['200_sma'], name='200 SMA', line=dict(color='#FF9900', dash='dot')))
        fig.add_hline(y=poc, line_color="#D4AF37", line_dash="dash", annotation_text="POC")
        fig.update_layout(template="plotly_dark", height=450, xaxis_rangeslider_visible=False, paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig, use_container_width=True)

        # --- CORE ELEMENT: AUTOGENERATED RANGE ---
        st.divider()
        mult = 3.2 if bias_input == "Bearish 📉" else 2.2 if bias_input == "Bullish 🚀" else 2.7
        auto_low, auto_high = price - (atr * mult), price + (atr * mult)
        
        st.markdown(f"### **Autogenerated Yield Range: ${auto_low:,.2f} — ${auto_high:,.2f}**")
        m_low, m_high = st.slider("Manual Adjust", float(price*0.3), float(price*1.7), (float(auto_low), float(auto_high)), 0.10)
        
        # Safety Alert
        if liq_price > 0 and m_low <= liq_price:
            st.error(f"⚠️ DANGER: Range Bottom (${m_low:,.2f}) is below Liquidation Price (${liq_price:,.2f})!")

        # CORE ELEMENT: YIELD MATRIX (7 HORIZONS)
        daily_p = (capital * lev * 0.0017) * ((price * 0.35) / max(m_high - m_low, 0.01))
        st.subheader(f"Yield Forecaster (Daily: ${daily_p:,.2f})")
        y_cols = st.columns(7)
        periods = {"1H": 1/24, "3H": 3/24, "6H": 6/24, "12H": 0.5, "1D": 1, "1W": 7, "1M": 30}
        for i, (lab, m) in enumerate(periods.items()):
            y_cols[i].metric(lab, f"${(daily_p * m):,.2f}")

if __name__ == "__main__":
    get_sreejan_forecaster()
